### ISSUE TITLE
does this have a dependency on "default" to work?  Does it work with "mineclone2" addon?

### ISSUE THREAD

**Issue by hiro5id** [minetest-mapserver/mapserver#132]

**Comment by BuckarooBanzay** [comment]
The mod here: https://github.com/minetest-mapserver/mapserver_mod has no hard depency to `default` anymore (since https://github.com/minetest-mapserver/mapserver_mod/commit/73ce10527444907183ba71fd9c898f68a7d147fb) and _should_ work with mineclone2

Please file an issue with the error if possible if something should be buggy though :+1:

**Comment by hiro5id** [comment]
Ok thanks @BuckarooBanzay It is good to know that the complementary mod for the mapserver doesn't have any dependencies on default...    but I was mostly asking about mapserver itself. I only ask because when I searched for `default:` within this project i found a bunch of hits in files such as `/static/colors/miles.txt` `/doc/lua_api.txt` `/doc/world_format.txt`  `/static/colors/vanessa.txt`. etc...

Are those superficial or co-incidence ?

**Comment by BuckarooBanzay** [comment]
> Are those superficial or co-incidence ?

Those are the color-mappings for most of the available blocks/mods, `default` is one of them
